extended-crawler:
  build: .
  command: python -u controller.py
  volumes:
    - .:/todo
    # - /data/Congestion/stream:/data/Congestion/stream
    - /home/ubuntu/sao-paulo-test:/data
  links:
    - db
db:
  image: mongo:3.0.2
